//! Authoritative section type ids, contracts, and codecs.
//!
//! Each registered Rust row type defines one stable `type_id`, logical name,
//! on-disk columns, sort and identity keys, collection semantics, and optional
//! collection gates. Layout versions can share a logical name; readers use the
//! contracts to union their columns without guessing from Parquet metadata.
//!
//! The sealed [`Section`] trait couples a contract to its encoder, decoder, and
//! timestamp range. The internal `kronika-derive` macro generates those pieces
//! from one annotated struct. [`lint`] and [`lint_references`] reject invalid
//! ids, keys, column classes, and cross-section gate references.
//!
//! Encoded and decoded sections are limited to [`MAX_SECTION_BYTES`],
//! [`MAX_SECTION_ROWS`], and [`MAX_ROW_GROUPS`]. [`VerifiedSection`] requires a
//! caller-supplied CRC check before Parquet sees the bytes. These checks bound
//! ordinary resource use and accidental corruption; they do not authenticate
//! a deliberately rebuilt segment.
//!
//! `PostgreSQL`- and Linux-specific meaning belongs here in declarative
//! contracts. Collection, storage, cross-segment queries, and HTTP responses
//! belong to their respective crates.
#![allow(
    clippy::multiple_crate_versions,
    reason = "the registry's arrow/parquet stack pulls duplicate transitive versions outside this crate"
)]

// The codec generated by `#[derive(Section)]` refers to this crate by name,
// so it must be nameable from inside the crate too.
extern crate self as kronika_registry;

mod codec;
mod contract;
mod generic;
mod parquet_preflight;
mod pool;
mod section;
mod type_id;

// Closes `Section` to downstream impls while keeping the public trait usable as
// a bound.
mod sealed {
    #[allow(
        unnameable_types,
        reason = "sealing Section means Sealed is reachable (as its supertrait) but deliberately not nameable downstream"
    )]
    pub trait Sealed {}
}

pub use codec::{
    CodecError, DecodeStats, DecodedSection, ListColumn, MAX_DECODED_SECTION_BYTES, MAX_ROW_GROUPS,
    MAX_SECTION_BYTES, MAX_SECTION_ROWS, SEALED_DATA_PAGE_BYTES, SEALED_ZSTD_LEVEL,
    SealedPlainColumnSize, VerifiedSection, arrow_schema, encode_sealed_batches, nullable_bool,
    nullable_column, opt_bool, opt_primitive, read_list_i32, required_bool, required_column,
    sealed_data_body_bound, sealed_plain_body_bound, write_bool, write_bool_nullable,
    write_list_i32, write_nullable, write_required,
};
pub use parquet_preflight::{
    ParquetDecodeProfile, parquet_decode_profile, plain_parquet_decode_profile,
    validate_parquet_decode_work, validate_plain_parquet_decode_work,
};
// Only the in-crate derive and tests need the shared section-body entry points.
pub(crate) use codec::{check_row_cap, decode_batches, decode_section, encode_section};
pub use codec::{
    collection_coverage, instance_metadata, os_cgroup_cpu, os_cgroup_io, os_cgroup_mapping,
    os_cgroup_memory, os_cgroup_pids, os_cpu, os_diskstats, os_interrupts, os_kernel_limits,
    os_loadavg, os_meminfo, os_mountinfo, os_netdev, os_netstat, os_nfs, os_numa, os_process,
    os_process_status, os_psi, os_snmp, os_snmp6, os_softirq, os_stat, os_topology, os_vmstat,
    snapshot_coverage,
};
pub use contract::{
    CollectionGate, Column, ColumnClass, ColumnType, LintError, RowGateOverride, SectionColumnRef,
    Semantics, StrId, Ts, TypeContract, lint, lint_references,
};
pub use generic::{Cell, Row, decode_rows};
pub use pool::{BytesPool, PoolStats};
pub use section::Section;
#[cfg(test)]
pub(crate) use section::assert_roundtrips;
pub use type_id::{SectionClass, TypeId};

// One `Bytes` for the decode API and derived codecs to name.
pub use bytes::Bytes;

// Section types are defined in this crate; the derive macro is not exported.
pub(crate) use kronika_derive::Section;

// Type tokens named by generated codecs.
pub use arrow_array::types::{
    Float32Type, Float64Type, Int8Type, Int16Type, Int32Type, Int64Type, UInt8Type, UInt16Type,
    UInt32Type, UInt64Type,
};

/// `type_id` of a `dict.strings` section (decoded directly by readers).
pub const DICT_STRINGS_TYPE_ID: u32 = 3_001_001;
/// `type_id` of a `dict.blobs` section. See [`DICT_STRINGS_TYPE_ID`].
pub const DICT_BLOBS_TYPE_ID: u32 = 3_002_001;

/// Return the registry section name for a raw `type_id`.
#[must_use]
pub fn section_name(type_id: u32) -> Option<&'static str> {
    match type_id {
        DICT_STRINGS_TYPE_ID => Some("dict.strings"),
        DICT_BLOBS_TYPE_ID => Some("dict.blobs"),
        _ => registry()
            .iter()
            .find(|contract| contract.type_id.get() == type_id)
            .map(|contract| contract.name),
    }
}

/// Every type id known to this build, in registry order.
#[must_use]
pub const fn registry() -> &'static [TypeContract] {
    &[
        instance_metadata::InstanceMetadata::CONTRACT,
        collection_coverage::CollectionCoverageV1::CONTRACT,
        snapshot_coverage::SnapshotCoverageV1::CONTRACT,
        os_process::OsProcess::CONTRACT,
        os_process_status::OsProcessStatus::CONTRACT,
        os_cpu::OsCpu::CONTRACT,
        os_stat::OsStat::CONTRACT,
        os_meminfo::OsMeminfo::CONTRACT,
        os_loadavg::OsLoadavg::CONTRACT,
        os_vmstat::OsVmstat::CONTRACT,
        os_psi::OsPsi::CONTRACT,
        os_diskstats::OsDiskstats::CONTRACT,
        os_netdev::OsNetdev::CONTRACT,
        os_snmp::OsSnmp::CONTRACT,
        os_netstat::OsNetstat::CONTRACT,
        os_mountinfo::OsMountinfo::CONTRACT,
        os_topology::OsTopology::CONTRACT,
        os_cgroup_mapping::OsCgroupMapping::CONTRACT,
        os_cgroup_cpu::OsCgroupCpu::CONTRACT,
        os_cgroup_memory::OsCgroupMemory::CONTRACT,
        os_cgroup_io::OsCgroupIo::CONTRACT,
        os_cgroup_pids::OsCgroupPids::CONTRACT,
        os_interrupts::OsInterrupts::CONTRACT,
        os_softirq::OsSoftirq::CONTRACT,
        os_kernel_limits::OsKernelLimits::CONTRACT,
        os_numa::OsNuma::CONTRACT,
        os_snmp6::OsSnmp6::CONTRACT,
        os_nfs::OsNfsClient::CONTRACT,
        os_nfs::OsNfsServer::CONTRACT,
    ]
}

/// Decode a verified section body using the contract selected by `type_id`.
///
/// # Errors
///
/// Returns [`CodecError`] for unknown `type_id`, schema mismatch, caps, or
/// Parquet decode failures.
pub fn decode_any(type_id: u32, section: VerifiedSection) -> Result<DecodedSection, CodecError> {
    let contract = registry()
        .iter()
        .find(|contract| contract.type_id.get() == type_id)
        .ok_or(CodecError::UnknownType { type_id })?;
    let bytes_in = section.len();
    decode_batches(contract, section).map_err(|source| CodecError::Section {
        type_id,
        bytes_in,
        source: Box::new(source),
    })
}

/// Decode a section read into a pooled buffer.
///
/// # Errors
///
/// Returns [`CodecError`] when length, CRC, type lookup, or decoding fails.
pub fn decode_pooled(
    pool: &BytesPool,
    type_id: u32,
    expected_len: usize,
    expected_crc: u32,
    crc32c: impl FnOnce(&[u8]) -> u32,
    fill: impl FnOnce(&mut Vec<u8>),
) -> Result<DecodedSection, CodecError> {
    if expected_len > MAX_SECTION_BYTES {
        return Err(CodecError::SectionTooLarge {
            len: expected_len,
            max: MAX_SECTION_BYTES,
        });
    }
    let bytes = pool.load(fill);
    // Guard against a buggy fill that writes more than the caller announced.
    if bytes.len() > MAX_SECTION_BYTES {
        return Err(CodecError::SectionTooLarge {
            len: bytes.len(),
            max: MAX_SECTION_BYTES,
        });
    }
    let bytes_in = bytes.len();
    let section = VerifiedSection::verify(bytes, expected_crc, crc32c).map_err(|source| {
        CodecError::Section {
            type_id,
            bytes_in,
            source: Box::new(source),
        }
    })?;
    decode_any(type_id, section)
}

/// Run the registry linter over every known type.
///
/// # Errors
///
/// Returns all linter errors found in registered contracts.
pub fn lint_registry() -> Result<(), Vec<LintError>> {
    lint(registry())?;
    lint_references(registry())
}

#[cfg(test)]
mod tests {
    use arrow_array::ArrayRef;
    use arrow_array::array::new_empty_array;
    use bytes::Bytes;

    use super::{
        BytesPool, CodecError, DICT_BLOBS_TYPE_ID, DICT_STRINGS_TYPE_ID, VerifiedSection,
        arrow_schema, decode_any, decode_pooled, encode_section, lint_registry, registry,
        section_name,
    };

    #[test]
    fn the_registry_is_clean() {
        assert_eq!(lint_registry(), Ok(()));
    }

    #[test]
    fn registry_is_not_empty() {
        assert!(!registry().is_empty());
    }

    /// Registry wiring check with no per-type branch.
    #[test]
    fn every_registered_type_decodes_an_empty_section() {
        for contract in registry() {
            let schema = arrow_schema(contract);
            let columns: Vec<ArrayRef> = schema
                .fields()
                .iter()
                .map(|field| new_empty_array(field.data_type()))
                .collect();
            let bytes = encode_section(contract, columns).expect("encode empty section");
            let bytes_in = bytes.len();
            let id = contract.type_id.get();
            let decoded =
                decode_any(id, VerifiedSection::for_test(bytes.into())).expect("decode_any");
            assert_eq!(decoded.stats.type_id, id, "stats carries the type_id");
            assert_eq!(
                decoded.stats.rows, 0,
                "type {id} decoded a non-empty section"
            );
            assert_eq!(
                decoded.stats.bytes_in, bytes_in,
                "stats.bytes_in matches input"
            );
        }
    }

    #[test]
    fn decode_pooled_reads_into_a_pooled_buffer_and_decodes() {
        let pool = BytesPool::new(2, 1 << 20);
        let contract = &registry()[0];
        let id = contract.type_id.get();
        let columns: Vec<ArrayRef> = arrow_schema(contract)
            .fields()
            .iter()
            .map(|field| new_empty_array(field.data_type()))
            .collect();
        let encoded = encode_section(contract, columns).expect("encode empty section");
        // Stand-in CRC = byte length; production code passes kronika-format's.
        let crc = |b: &[u8]| u32::try_from(b.len()).unwrap_or(u32::MAX);
        let expected = crc(&encoded);
        let decoded = decode_pooled(&pool, id, encoded.len(), expected, crc, |buf| {
            buf.extend_from_slice(&encoded);
        })
        .expect("decode_pooled");
        assert_eq!(decoded.stats.type_id, id);
    }

    #[test]
    fn decode_any_rejects_an_unregistered_type() {
        // Structurally valid (class 2, source 999, version 999) but not in the
        // registry, so decode_any must reject it rather than decode garbage.
        assert!(matches!(
            decode_any(2_999_999, VerifiedSection::for_test(Bytes::new())),
            Err(CodecError::UnknownType { type_id: 2_999_999 })
        ));
    }

    #[test]
    fn section_name_uses_registry_contracts_and_dictionary_names() {
        assert_eq!(section_name(1_021_001), Some("instance_metadata"));
        assert_eq!(section_name(1_104_001), Some("os_meminfo"));
        assert_eq!(section_name(DICT_STRINGS_TYPE_ID), Some("dict.strings"));
        assert_eq!(section_name(DICT_BLOBS_TYPE_ID), Some("dict.blobs"));
        assert_eq!(section_name(9_999_999), None);
    }
}
