use super::{WorkloadConfig, connect_as, naming};
use rand::rngs::StdRng;
use rand::{Rng as _, SeedableRng as _};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;
use tokio_postgres::Client;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Action {
    Insert,
    Update,
    Select,
    /// Matches no rows so the demo table stays bounded.
    Delete,
    /// A query that deliberately crosses the 5s known-bad boundary.
    SlowQuery,
    /// Emits a syntax error.
    BadStatement,
    /// Emits `PgBouncer`'s "no such database" event.
    BadDatabase,
}

pub(crate) const fn next_action(roll: u32) -> Action {
    match roll % 100 {
        0..=29 => Action::Insert,
        30..=54 => Action::Update,
        55..=89 => Action::Select,
        _ => Action::Delete,
    }
}

const JITTER_MS: [u64; 3] = [200, 500, 900];
const WORKLOAD_SEED: u64 = 0x4b52_4f4e_494b_4100;
const ROW_KEY_SPACE: u64 = 10_000;
const SESSION_APPLICATIONS: [&str; 4] = [
    "checkout-api",
    "catalog-api",
    "payments-worker",
    "fulfillment-worker",
];

pub(crate) const fn session_application_name(session: u32) -> &'static str {
    SESSION_APPLICATIONS[session as usize % SESSION_APPLICATIONS.len()]
}

fn session_rng(session: u32) -> StdRng {
    StdRng::seed_from_u64(WORKLOAD_SEED ^ u64::from(session))
}

pub(crate) fn bounded_row_id(random: u64) -> i64 {
    i64::try_from(random % ROW_KEY_SPACE + 1).expect("bounded row ID must fit in i64")
}

pub(crate) async fn run_session(session: u32, config: &WorkloadConfig, stop: &Arc<AtomicBool>) {
    let Ok(client) = connect_as(&config.dsn, session_application_name(session)).await else {
        eprintln!("kronika-demo: workload session {session} could not connect");
        return;
    };
    let mut rng = session_rng(session);
    while !stop.load(Ordering::Relaxed) {
        let table = naming::table_name(
            rng.gen_range(0..config.schemas),
            rng.gen_range(0..config.tables_per_schema),
        );
        let action = next_action(rng.gen_range(0..100));
        let pause_ms = JITTER_MS[rng.gen_range(0..JITTER_MS.len())];
        let id = bounded_row_id(rng.r#gen());
        if let Err(error) = perform(&client, config, &table, action, id).await {
            eprintln!("kronika-demo: session {session} {action:?} on {table} failed: {error:#}");
        }
        tokio::time::sleep(Duration::from_millis(pause_ms)).await;
    }
}

// PgBouncer transaction pooling cannot preserve prepared statements between calls.
// All inlined values are numbers generated by this module.
pub(super) async fn perform(
    client: &Client,
    config: &WorkloadConfig,
    table: &str,
    action: Action,
    id: i64,
) -> anyhow::Result<()> {
    if let Some(sql) = ordinary_sql(table, action, id) {
        client.batch_execute(&sql).await?;
        return Ok(());
    }
    match action {
        Action::Insert | Action::Update | Action::Select | Action::Delete => unreachable!(),
        Action::SlowQuery => {
            client.batch_execute("select pg_sleep(6)").await?;
        }
        Action::BadStatement => {
            // The failure is the event.
            drop(client.batch_execute("slect 1").await);
        }
        Action::BadDatabase => {
            drop(connect_as(&format!("{} dbname=nope", config.dsn), "misconfigured-api").await);
        }
    }
    Ok(())
}

pub(crate) fn ordinary_sql(table: &str, action: Action, id: i64) -> Option<String> {
    match action {
        Action::Insert => Some(format!(
            "insert into {table} (id) values ({id}) on conflict do nothing"
        )),
        Action::Update => Some(format!("update {table} set id = id where id = {id}")),
        Action::Select => Some(format!("select * from {table} limit 50")),
        Action::Delete => Some(format!("delete from {table} where false")),
        Action::SlowQuery | Action::BadStatement | Action::BadDatabase => None,
    }
}

#[cfg(test)]
mod tests;
